import sqlite3
from pathlib import Path
BASE_DIR=Path(__file__).resolve().parent.parent
DB_PATH=BASE_DIR/'database'/'app.db'
def get_connection():
    DB_PATH.parent.mkdir(parents=True,exist_ok=True); c=sqlite3.connect(DB_PATH,timeout=30); c.row_factory=sqlite3.Row; c.execute('PRAGMA foreign_keys=ON'); return c
def _cols(c,t): return {r[1] for r in c.execute(f'PRAGMA table_info({t})').fetchall()}
def _add(c,t,col,definition):
    if col not in _cols(c,t): c.execute(f'ALTER TABLE {t} ADD COLUMN {col} {definition}')
def init_database():
    c=get_connection(); c.executescript('''
    CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,telegram_id INTEGER UNIQUE NOT NULL,role TEXT NOT NULL DEFAULT 'owner',is_active INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,telegram_id INTEGER UNIQUE NOT NULL,username TEXT,first_name TEXT,balance INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS panels(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,url TEXT NOT NULL,username TEXT NOT NULL,password TEXT NOT NULL,access_token TEXT,status TEXT NOT NULL DEFAULT 'unknown',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'suggested',data_gb INTEGER NOT NULL DEFAULT 0,days INTEGER NOT NULL DEFAULT 0,max_users INTEGER NOT NULL DEFAULT 0,price INTEGER NOT NULL DEFAULT 0,description TEXT DEFAULT '',capacity INTEGER NOT NULL DEFAULT 0,sold INTEGER NOT NULL DEFAULT 0,enabled INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS custom_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 1,min_gb INTEGER NOT NULL DEFAULT 1,max_gb INTEGER NOT NULL DEFAULT 0,price_per_gb INTEGER NOT NULL DEFAULT 0,min_days INTEGER NOT NULL DEFAULT 1,max_days INTEGER NOT NULL DEFAULT 0,price_per_month INTEGER NOT NULL DEFAULT 0,price_limited_unlimited INTEGER NOT NULL DEFAULT 0,price_per_day INTEGER NOT NULL DEFAULT 0,ask_duration INTEGER NOT NULL DEFAULT 1,default_days INTEGER NOT NULL DEFAULT 30,users_enabled INTEGER NOT NULL DEFAULT 0,min_users INTEGER NOT NULL DEFAULT 1,max_users INTEGER NOT NULL DEFAULT 0,price_per_user INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS payment_methods(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL DEFAULT 'کارت به کارت',kind TEXT NOT NULL DEFAULT 'card_to_card',card_number TEXT NOT NULL DEFAULT '',card_holder TEXT NOT NULL DEFAULT '',enabled INTEGER NOT NULL DEFAULT 1,auto_approve INTEGER NOT NULL DEFAULT 0,auto_approve_minutes INTEGER NOT NULL DEFAULT 5,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,panel_id INTEGER,product_id INTEGER,kind TEXT NOT NULL DEFAULT 'suggested',total_amount INTEGER NOT NULL DEFAULT 0,wallet_amount INTEGER NOT NULL DEFAULT 0,card_amount INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'awaiting_payment',username TEXT,password TEXT,custom_gb INTEGER DEFAULT 0,custom_days INTEGER DEFAULT 0,custom_users INTEGER DEFAULT 0,target_service_id INTEGER,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,receipt_at TIMESTAMP,approved_at TIMESTAMP,rejected_at TIMESTAMP,auto_approve_at TIMESTAMP,error TEXT,receipt_file_id TEXT,receipt_message_id INTEGER,approved_by INTEGER,rejected_by INTEGER);
    CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,user_id INTEGER NOT NULL,panel_id INTEGER NOT NULL,product_id INTEGER,username TEXT NOT NULL,password TEXT NOT NULL,pg_admin_id INTEGER,data_limit_bytes INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',started_at TIMESTAMP,expires_at TIMESTAMP,suspended_until TIMESTAMP,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount INTEGER NOT NULL,type TEXT NOT NULL,description TEXT DEFAULT '',order_id INTEGER,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS reports_config(id INTEGER PRIMARY KEY CHECK(id=1),chat_id INTEGER,enabled INTEGER NOT NULL DEFAULT 0,topics_json TEXT DEFAULT '{}');
    CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '');
    CREATE TABLE IF NOT EXISTS admin_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,action TEXT NOT NULL,details TEXT DEFAULT '',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS coupons(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,kind TEXT NOT NULL DEFAULT 'percent',value INTEGER NOT NULL DEFAULT 0,max_users INTEGER NOT NULL DEFAULT 0,max_uses_per_user INTEGER NOT NULL DEFAULT 1,expires_at TIMESTAMP,enabled INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS coupon_usages(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL,user_id INTEGER NOT NULL,order_id INTEGER,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS wallet_topups(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'awaiting_receipt',receipt_file_id TEXT,receipt_message_id INTEGER,approved_by INTEGER,rejected_by INTEGER,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,approved_at TIMESTAMP,rejected_at TIMESTAMP);
    CREATE TABLE IF NOT EXISTS user_controls(user_id INTEGER PRIMARY KEY,blocked INTEGER NOT NULL DEFAULT 0);
    ''')
    for col,definition in [('balance','INTEGER NOT NULL DEFAULT 0'),('username','TEXT'),('first_name','TEXT')]: _add(c,'users',col,definition)
    for col,definition in [('access_token','TEXT'),('status',"TEXT NOT NULL DEFAULT 'unknown'")]: _add(c,'panels',col,definition)
    for col,definition in [('description',"TEXT DEFAULT ''"),('capacity','INTEGER NOT NULL DEFAULT 0'),('sold','INTEGER NOT NULL DEFAULT 0'),('enabled','INTEGER NOT NULL DEFAULT 1'),('kind',"TEXT NOT NULL DEFAULT 'suggested'")]: _add(c,'products',col,definition)
    for col,definition in [('enabled','INTEGER NOT NULL DEFAULT 1'),('min_gb','INTEGER NOT NULL DEFAULT 1'),('max_gb','INTEGER NOT NULL DEFAULT 0'),('price_per_gb','INTEGER NOT NULL DEFAULT 0'),('min_days','INTEGER NOT NULL DEFAULT 1'),('max_days','INTEGER NOT NULL DEFAULT 0'),('price_per_month','INTEGER NOT NULL DEFAULT 0'),('price_limited_unlimited','INTEGER NOT NULL DEFAULT 0'),('price_per_day','INTEGER NOT NULL DEFAULT 0'),('ask_duration','INTEGER NOT NULL DEFAULT 1'),('default_days','INTEGER NOT NULL DEFAULT 30')]: _add(c,'custom_settings',col,definition)
    for col,definition in [('card_number',"TEXT NOT NULL DEFAULT ''"),('card_holder',"TEXT NOT NULL DEFAULT ''"),('kind',"TEXT NOT NULL DEFAULT 'card_to_card'"),('auto_approve','INTEGER NOT NULL DEFAULT 0'),('enabled','INTEGER NOT NULL DEFAULT 1'),('auto_approve_minutes','INTEGER NOT NULL DEFAULT 5')]: _add(c,'payment_methods',col,definition)
    for col,definition in [('coupon_code','TEXT'),('discount_amount','INTEGER NOT NULL DEFAULT 0'),('user_id','INTEGER'),('panel_id','INTEGER'),('product_id','INTEGER'),('kind',"TEXT NOT NULL DEFAULT 'suggested'"),('total_amount','INTEGER NOT NULL DEFAULT 0'),('wallet_amount','INTEGER NOT NULL DEFAULT 0'),('card_amount','INTEGER NOT NULL DEFAULT 0'),('status',"TEXT NOT NULL DEFAULT 'awaiting_payment'"),('username','TEXT'),('password','TEXT'),('custom_gb','INTEGER DEFAULT 0'),('custom_days','INTEGER DEFAULT 0'),('custom_users','INTEGER DEFAULT 0'),('receipt_at','TIMESTAMP'),('approved_at','TIMESTAMP'),('rejected_at','TIMESTAMP'),('auto_approve_at','TIMESTAMP'),('error','TEXT'),('receipt_file_id','TEXT'),('receipt_message_id','INTEGER'),('approved_by','INTEGER'),('rejected_by','INTEGER')]: _add(c,'orders',col,definition)
    for col,definition in [('coupon_code','TEXT'),('discount_amount','INTEGER NOT NULL DEFAULT 0')]: _add(c,'orders',col,definition)
    for col,definition in [('data_limit_bytes','INTEGER NOT NULL DEFAULT 0')]: _add(c,'services',col,definition)
    for col,definition in [('order_id','INTEGER'),('status',"TEXT NOT NULL DEFAULT 'pending'")]: _add(c,'coupon_usages',col,definition)
    c.execute('INSERT OR IGNORE INTO custom_settings(id) VALUES(1)'); c.execute('INSERT OR IGNORE INTO reports_config(id) VALUES(1)');
    defaults={'order_summary':'1','notify_admin_receipt':'1','notify_report_receipt':'1','bot_name':'','welcome_text':'','support_text':'','support_username':'','support_link':'','min_wallet_topup':'100000','service_renewal_enabled':'1','service_volume_add_enabled':'1','service_revoke_enabled':'1'}
    for k,v in defaults.items(): c.execute('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)',(k,v))
    c.commit(); c.close()
